#!/usr/bin/with-contenv bash

# Install custom opcache configuration
for conf_dir in /etc/php*/conf.d/
do
    if [[ ! -f "$conf_dir/z-opcache.conf" ]]
    then
        cp /defaults/z-opcache.conf "$conf_dir/z-opcache.conf"
    fi
done
